"""
Evaluate a trained joint flow matching model:

  1. Distributional fidelity (FID / KID) per concentration and pooled,
     comparing real cells against cells generated by inverting real DMSO
     controls to noise and re-integrating the forward ODE at each target
     concentration (Sec. 4.3 / Table 2 in the paper).
  2. Dose-conditioned cell morphs by inversion: encode a real control cell,
     invert to noise, then forward-integrate at each target concentration
     (Sec. 3.3), producing a morph strip per source cell that preserves
     cell identity.

FID/KID require an offline Inception-v3 checkpoint (see --inception_path and
the README for how to obtain and point to it if the eval host has no
internet access).
"""
import argparse
import json
import os
import pathlib
import re

import numpy as np
import pandas as pd
import scipy.linalg
import torch
import torch.nn.functional as F
import yaml
from PIL import Image, ImageDraw, ImageFont
from torchvision import transforms
import torchvision.utils as vutils
from tqdm import tqdm

from src.vae import MicroscopyVAE
from src.flow_model import JointFlowUNet
from src.dataset import FlowCompoundDataset
from src.utils import load_ema_model


# ─────────────────────────────────────────────────────────────────────────────
# Inception / FID / KID
# ─────────────────────────────────────────────────────────────────────────────
def load_inception(weights_path, device):
    """Load an offline Inception-v3 checkpoint for FID/KID feature extraction.
    See the README for how to obtain this file on a host without internet access."""
    import torchvision.models as tv
    import torch.nn as nn
    model = tv.inception_v3(weights=None, aux_logits=True, transform_input=False)
    model.load_state_dict(torch.load(weights_path, map_location=device))
    model.fc = nn.Identity()
    model.aux_logits = False
    model = model.to(device).eval()
    for p in model.parameters():
        p.requires_grad = False
    return model


@torch.no_grad()
def inception_features(images, inception, device, batch_size=32):
    """images: [N, C, H, W] in [0, 1]. Returns [N, 2048] numpy."""
    mean = torch.tensor([0.485, 0.456, 0.406], device=device).view(1, 3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225], device=device).view(1, 3, 1, 1)
    feats = []
    for i in range(0, len(images), batch_size):
        batch = images[i:i + batch_size].to(device)
        batch = F.interpolate(batch, size=(299, 299), mode='bilinear', align_corners=False)
        batch = (batch - mean) / std
        feats.append(inception(batch).cpu().numpy())
    return np.concatenate(feats, axis=0)


def frechet_distance(mu1, sigma1, mu2, sigma2):
    diff = mu1 - mu2
    covmean, _ = scipy.linalg.sqrtm(sigma1 @ sigma2, disp=False)
    if np.iscomplexobj(covmean):
        covmean = covmean.real
    return float(diff @ diff + np.trace(sigma1 + sigma2 - 2 * covmean))


def kid_unbiased(real_feats, gen_feats, degree=3):
    """Unbiased KID via a degree-3 polynomial kernel on Inception features."""
    m, n = len(real_feats), len(gen_feats)
    d = real_feats.shape[1]

    def poly(X, Y):
        return (X @ Y.T / d + 1.0) ** degree

    k_rr, k_gg, k_rg = poly(real_feats, real_feats), poly(gen_feats, gen_feats), poly(real_feats, gen_feats)
    kid = ((k_rr.sum() - np.trace(k_rr)) / (m * (m - 1))
           + (k_gg.sum() - np.trace(k_gg)) / (n * (n - 1))
           - 2 * k_rg.mean())
    return float(kid)


# ─────────────────────────────────────────────────────────────────────────────
# VAE encode/decode, ODE solvers
# ─────────────────────────────────────────────────────────────────────────────
@torch.no_grad()
def encode(vae, images, scale_factor, device):
    mu, _ = vae.encode(images.to(device))
    return mu * scale_factor


@torch.no_grad()
def decode(vae, latents, scale_factor):
    return vae.decode(latents / scale_factor).clamp(0, 1)


@torch.no_grad()
def invert_ode(model, z_latent, c_value, device, steps=200):
    """Invert an encoded latent -> noise at a fixed concentration (Eq. 10)."""
    B = z_latent.shape[0]
    z = z_latent.clone()
    c_batch = torch.full((B,), float(c_value), dtype=torch.float32, device=device)

    dt = 1.0 / steps
    for i in reversed(range(steps)):
        t_z = torch.full((B,), i / steps, device=device)
        t_c = torch.ones(B, device=device)
        v_z, _ = model(z, t_z, t_c, c_scalar=c_batch)
        z = z - v_z * dt
    return z


@torch.no_grad()
def forward_ode(model, z_start, c_value, device, steps=200):
    """Forward-integrate a latent from t_z=0 to t_z=1 at a fixed concentration
    (Eq. 11 for morphing by inversion; also used for pure-noise generation)."""
    B = z_start.shape[0]
    z = z_start.clone()
    c_t = torch.full((B,), float(c_value), dtype=torch.float32, device=device)

    dt = 1.0 / steps
    for i in range(steps):
        t_z = torch.full((B,), i / steps, device=device)
        t_c = torch.ones(B, device=device)
        v_z, _ = model(z, t_z, t_c, c_scalar=c_t)
        z = z + v_z * dt
    return z


# ─────────────────────────────────────────────────────────────────────────────
# Model / checkpoint loading
# ─────────────────────────────────────────────────────────────────────────────
def load_flow_model(cfg, ckpt_path, device):
    model = JointFlowUNet(
        dim=cfg['model']['dim'],
        dim_mults=tuple(cfg['model']['dim_mults']),
        channels=4,
        out_dim=4,
        resnet_block_groups=cfg['model']['resnet_block_groups'],
    ).to(device)
    ckpt = torch.load(ckpt_path, map_location=device)
    raw = ckpt.get('ema_state_dict', ckpt.get('model_state_dict'))
    state = {k.replace("module.", ""): v for k, v in raw.items() if k != "n_averaged"}
    model.load_state_dict(state)
    model.eval()
    print(f"[INFO] Loaded JointFlowUNet | epoch={ckpt.get('epoch', 0)} "
          f"| loss={ckpt.get('train_loss', 0.0):.6f}")
    return model


def resolve_checkpoint(exp_dir):
    exp_dir = pathlib.Path(exp_dir)
    best = exp_dir / "best_model.pt"
    if best.exists():
        return best
    ckpt_dir = exp_dir / "checkpoints"
    ckpt_files = list(ckpt_dir.glob("*.pt")) if ckpt_dir.exists() else []
    if not ckpt_files:
        raise FileNotFoundError(f"No checkpoint found in {exp_dir}")

    def _epoch(p):
        nums = re.findall(r'\d+', p.stem)
        return int(nums[-1]) if nums else -1

    return max((f for f in ckpt_files if _epoch(f) != -1), key=_epoch)


# ─────────────────────────────────────────────────────────────────────────────
# FID / KID via inversion (Table 2)
# ─────────────────────────────────────────────────────────────────────────────
@torch.no_grad()
def eval_fid_kid(model, vae, ds, scale_factor, device, eval_dir, drug,
                  steps, invert_steps, inception_path, batch_size=32):
    """
    Invert real DMSO controls -> noise, forward-generate at every target
    concentration, and compute FID/KID against real cells at that
    concentration. Reports per-concentration and pooled metrics.
    """
    if not inception_path or not pathlib.Path(inception_path).exists():
        raise FileNotFoundError(
            f"Inception checkpoint not found at '{inception_path}'. "
            "Pass --inception_path pointing to a local inception_v3 state dict "
            "(see the README for how to obtain one offline)."
        )
    inception = load_inception(inception_path, device)

    concs_drug = sorted(c for c in ds.df_tgt['concentration'].unique() if c > 0)
    c_dmso = ds.get_model_conc(0.0)
    tf = ds.transform

    dmso_rows = ds.df_tgt[np.isclose(ds.df_tgt['concentration'].values, 0.0)]
    assert len(dmso_rows) > 0, "No DMSO cells found to invert."
    dmso_imgs = torch.stack([tf(Image.open(os.path.join(ds.data_root, r['relpath'])).convert('RGB')) for _, r in dmso_rows.iterrows()])

    print(f"[FID/KID] Inverting {len(dmso_imgs)} DMSO control cells...")
    z_noise = []
    for i in tqdm(range(0, len(dmso_imgs), batch_size), desc="Inverting", leave=False):
        batch = dmso_imgs[i:i + batch_size]
        z = encode(vae, batch, scale_factor, device)
        z_noise.append(invert_ode(model, z, c_dmso, device, steps=invert_steps).cpu())
    z_noise = torch.cat(z_noise, dim=0)
    n_src = len(z_noise)

    rows = []
    all_real, all_gen = [], []
    for c_raw in concs_drug:
        real_rows = ds.df_tgt[(ds.df_tgt['concentration'] > 0) & np.isclose(ds.df_tgt['concentration'].values, c_raw)]
        if len(real_rows) == 0:
            print(f"  [WARN] No real images at c={c_raw}, skipping")
            continue
        real_imgs = torch.stack([tf(Image.open(os.path.join(ds.data_root, r['relpath'])).convert('RGB')) for _, r in real_rows.iterrows()])

        c_model = ds.get_model_conc(c_raw)
        gen_list = []
        for j in range(0, n_src, batch_size):
            z_batch = z_noise[j:j + batch_size].to(device)
            z_gen = forward_ode(model, z_batch, c_model, device, steps=steps)
            gen_list.append(decode(vae, z_gen, scale_factor).cpu())
        gen_imgs = torch.cat(gen_list, dim=0)[:n_src]

        real_feats = inception_features(real_imgs, inception, device, batch_size)
        gen_feats = inception_features(gen_imgs, inception, device, batch_size)
        fid = frechet_distance(real_feats.mean(0), np.cov(real_feats, rowvar=False),
                                gen_feats.mean(0), np.cov(gen_feats, rowvar=False))
        kid = kid_unbiased(real_feats, gen_feats)

        rows.append(dict(concentration=float(c_raw), n_real=len(real_imgs), n_gen=len(gen_imgs), fid=fid, kid=kid))
        print(f"  c={c_raw:.4g}uM | N_real={len(real_imgs)} N_gen={len(gen_imgs)} | FID={fid:.2f} KID={kid:.4f}")

        all_real.append(real_feats)
        all_gen.append(gen_feats)

    if all_real:
        real_all, gen_all = np.concatenate(all_real), np.concatenate(all_gen)
        fid_pool = frechet_distance(real_all.mean(0), np.cov(real_all, rowvar=False),
                                     gen_all.mean(0), np.cov(gen_all, rowvar=False))
        kid_pool = kid_unbiased(real_all, gen_all)
        rows.append(dict(concentration="pooled", n_real=len(real_all), n_gen=len(gen_all), fid=fid_pool, kid=kid_pool))
        print(f"  POOLED | N_real={len(real_all)} N_gen={len(gen_all)} | FID={fid_pool:.2f} KID={kid_pool:.4f}")

    df = pd.DataFrame(rows)
    out_csv = eval_dir / f"fid_kid_{drug}.csv"
    df.to_csv(out_csv, index=False)
    print(f"[FID/KID] Saved -> {out_csv}")
    return df


# ─────────────────────────────────────────────────────────────────────────────
# Morph generation: by inversion
# ─────────────────────────────────────────────────────────────────────────────
def _font(size=13):
    try:
        # matplotlib bundles DejaVu Sans, giving a portable TTF across platforms
        import matplotlib
        font_path = os.path.join(matplotlib.get_data_path(), "fonts", "ttf", "DejaVuSans-Bold.ttf")
        return ImageFont.truetype(font_path, size)
    except Exception:
        return ImageFont.load_default()


def _label_columns(img_pil, labels):
    draw = ImageDraw.Draw(img_pil)
    font = _font()
    cell_w = img_pil.width // len(labels)
    for i, label in enumerate(labels):
        draw.text((i * cell_w + 4, 4), label, fill=(0, 0, 0), font=font)
        draw.text((i * cell_w + 3, 3), label, fill=(255, 255, 255), font=font)
    return img_pil


def _save_grid(cols, labels, out_path):
    n_rows = cols[0].shape[0]
    all_imgs = [cols[c][r] for r in range(n_rows) for c in range(len(cols))]
    grid = vutils.make_grid(torch.stack(all_imgs), nrow=len(cols), padding=2, normalize=True)
    img_pil = Image.fromarray(grid.mul(255).clamp(0, 255).permute(1, 2, 0).byte().numpy())
    img_pil = _label_columns(img_pil, labels)
    img_pil.save(out_path)


@torch.no_grad()
def generate_morphs_by_inversion(model, vae, ds, scale_factor, device, eval_dir, drug,
                                  steps, invert_steps, n_cells=8):
    """Morph real control cells across concentrations by inverting each cell to
    noise and re-integrating the forward ODE at every target concentration
    (Sec. 3.3): a morph strip per source cell that preserves cell identity."""
    concs_drug = sorted(c for c in ds.df_tgt['concentration'].unique() if c > 0)
    c_dmso = ds.get_model_conc(0.0)
    labels = ["control"] + [f"{c:.3g}uM" for c in concs_drug]

    dmso_rows = ds.df_tgt[np.isclose(ds.df_tgt['concentration'].values, 0.0)].iloc[:n_cells]
    n_cells = len(dmso_rows)
    tf = ds.transform
    src_imgs = torch.stack([tf(Image.open(os.path.join(ds.data_root, r['relpath'])).convert('RGB')) for _, r in dmso_rows.iterrows()])

    z_src = encode(vae, src_imgs, scale_factor, device)
    z_noise = invert_ode(model, z_src, c_dmso, device, steps=invert_steps)

    cols = [src_imgs]
    npz = {"src": src_imgs.numpy().astype(np.float32)}
    for c_raw in concs_drug:
        c_model = ds.get_model_conc(c_raw)
        z_gen = forward_ode(model, z_noise, c_model, device, steps=steps)
        imgs_gen = decode(vae, z_gen, scale_factor).cpu()
        cols.append(imgs_gen)
        npz[f"morph_{c_raw:.6g}".replace(".", "_")] = imgs_gen.numpy().astype(np.float32)

    np.savez(eval_dir / f"morphs_{drug}.npz", **npz)
    _save_grid(cols, labels, eval_dir / f"morphs_{drug}.png")
    print(f"[MORPH/inversion] {n_cells} cells x {len(concs_drug)} concentrations -> {eval_dir}")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    p = argparse.ArgumentParser(description="Evaluate the joint latent flow matching model")
    p.add_argument("--exp", type=str, required=True,
                    help="Experiment name under experiments/, e.g. latent_fm_joint_conc/<timestamp>_ONS76_C7_log10")
    p.add_argument("--split", type=str, default="test", choices=["val", "test"])
    p.add_argument("--steps", type=int, default=200, help="Forward ODE steps")
    p.add_argument("--invert_steps", type=int, default=200, help="Inversion ODE steps")
    p.add_argument("--n_morph_cells", type=int, default=8)
    p.add_argument("--batch_size", type=int, default=32)
    p.add_argument("--inception_path", type=str, default=None,
                    help="Path to an offline inception_v3 state dict (required for --skip_fid=False). "
                         "See the README if the eval host has no internet access.")
    p.add_argument("--skip_fid", action="store_true", help="Skip FID/KID (no Inception checkpoint needed).")
    p.add_argument("--skip_morphs", action="store_true", help="Skip morph generation.")
    p.add_argument("--data", type=str, default=None,
                    help="Override the metadata CSV baked into the checkpoint's config "
                         "(e.g. metadata/sample_metadata.csv, to demo a checkpoint — including "
                         "a downloaded pretrained one — against the small bundled sample instead "
                         "of the full dataset). With sample data, also pass --skip_fid: there "
                         "usually aren't enough images per concentration for a meaningful FID/KID.")
    p.add_argument("--data_root", type=str, default=None,
                    help="Override data_root; required together with --data.")
    args = p.parse_args()

    np.random.seed(42)
    torch.manual_seed(42)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    BASE_DIR = pathlib.Path(__file__).parent.resolve()
    exp_dir = BASE_DIR / "experiments" / args.exp
    if not exp_dir.exists():
        raise FileNotFoundError(f"Experiment not found: {exp_dir}")

    with open(exp_dir / "config.yaml") as f:
        cfg = yaml.safe_load(f)
    if args.data:
        assert args.data_root, "--data requires --data_root"
        cfg['data'], cfg['data_root'] = args.data, args.data_root
    t, m = cfg['training'], cfg['model']
    drug = t.get('drug', 'unknown')

    eval_dir = exp_dir / "evaluation"
    eval_dir.mkdir(exist_ok=True)

    # ── Load frozen VAE ───────────────────────────────────────────────────────
    vae = MicroscopyVAE(
        in_channels=cfg['vae']['in_channels'],
        latent_channels=cfg['vae']['latent_channels'],
        base_channels=cfg['vae'].get('base_channels', 64),
    ).to(device)
    vae, _ = load_ema_model(vae, BASE_DIR / cfg['vae']['checkpoint'], device)
    vae.eval()
    for prm in vae.parameters():
        prm.requires_grad = False

    # ── Load flow model ───────────────────────────────────────────────────────
    ckpt_path = resolve_checkpoint(exp_dir)
    model = load_flow_model(cfg, ckpt_path, device)

    scale_path = exp_dir / "latent_scale.pt"
    scale_factor = torch.load(scale_path)["scale_factor"] if scale_path.exists() else 1.0
    print(f"[INFO] Scale factor: {scale_factor:.4f}")

    # ── Dataset ───────────────────────────────────────────────────────────────
    ds = FlowCompoundDataset(
        csv_path=os.path.join(BASE_DIR, cfg['data']),
        cell_line=m['cell_line'],
        split=args.split,
        in_channels=cfg['vae']['in_channels'],
        transform=transforms.ToTensor(),
        data_root=os.path.join(BASE_DIR, cfg['data_root']),
        drug=drug,
        target_concentrations=t.get('target_concentrations', None),
        conc_transform=t.get('conc_transform', None),
        filtered_only=t.get('filtered_only', True),
        include_dmso_targets=t.get('include_dmso', True),
    )
    print(f"[INFO] Drug={drug} | concentrations={sorted(ds.df_tgt['concentration'].unique().tolist())}")

    # Tag output filenames with the data source so a run against sample_data/
    # doesn't overwrite results from a run against the real dataset.
    data_tag = pathlib.Path(cfg['data']).stem
    out_tag = drug if data_tag == "cell_lines_drug_compounds" else f"{drug}_{data_tag}"

    results = {}
    if not args.skip_fid:
        print("\n" + "=" * 70 + "\n[EVAL] FID / KID via inversion\n" + "=" * 70)
        df = eval_fid_kid(model, vae, ds, scale_factor, device, eval_dir, out_tag,
                           steps=args.steps, invert_steps=args.invert_steps,
                           inception_path=args.inception_path, batch_size=args.batch_size)
        results["fid_kid"] = df.to_dict(orient="records")

    if not args.skip_morphs:
        print("\n" + "=" * 70 + "\n[EVAL] Morph generation\n" + "=" * 70)
        generate_morphs_by_inversion(model, vae, ds, scale_factor, device, eval_dir, out_tag,
                                      steps=args.steps, invert_steps=args.invert_steps,
                                      n_cells=args.n_morph_cells)

    with open(eval_dir / f"summary_{out_tag}.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n[SUCCESS] All outputs -> {eval_dir}")


if __name__ == "__main__":
    main()
